### ISSUE TITLE
[template] considere adding default routesfor archiva and archiva-web services

### ISSUE THREAD

**Issue by dsimansk** [josefkarasek/openshift-archiva#1]
Hi @josefkarasek,
do you considere adding default routes to the template? I'd like to setup all needed configuration during app creation from template. I'm happy to work on a PR if it's needed.

Thanks in advance for your kind reply, may the force be with you!

**Comment by josefkarasek** [comment]
Hi,
I'm thinking about exposing web interface to enable greater customization. Don't see a reason in exposing archiva service since purpose of this project is to speed-up Java builds in Openshift 3 environment, not to provide hosting for dependencies. Archiva is a cache after all.

**Comment by dsimansk** [comment]
Actually I might have a different use case then. I've seen it more like cache deployed in common namespace and consumed by user's namespaces afterwards. Of course the route can be added easily through web console nowadays.

**Comment by josefkarasek** [comment]
Thanks for participating @dsimansk. Yes, the plan is to offer an artifact cache to all K8 namespaces. The service can be accessed through skyDNS as 'archiva.namespace.svc.cluster.local'. This is FQDN. If accessed by a pod in the same namespace, going with just the service name will do as well.

**Comment by dsimansk** [comment]
Indeed...
